site_name: Pàgina de Joel

theme:
  name: material
  code:
    highlight_theme: dracula
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Tema fosc
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Tema clar
  features:
    - content.code.copy
    - palette.toggle



nav:
  - Inici: index.md
  - Com fer el MkDocs: MkDocs.md
  - DAM:
    - PMDM: DAM/PMDM/Flutter.md
  - DAW:
    - DWEC: 
      - Base de dades : DAW/DWEC/BD.md
      - Backend en APIS amb Node.js : DAW/DWEC/Backend.md
    - DWES: 
      - Base de dades : DAW/DWES/BD.md
      - Backend en APIS amb Node.js : DAW/DWES/Backend.md
